### ISSUE TITLE
Sorting items inside grid list angular 2 material issue

### ISSUE THREAD

**Issue by eslammahgoub** [SortableJS/ngx-sortablejs#60]
I'm using angular 2 material and I had case of sorting items in grid list [here](https://material.angular.io/components/grid-list), there are Array of Categories and every 3 categories in one row in grid I'm using options of { sort: true, animation: 100 }; the item can drag but not clone or drop or sort,
any help.
**Reproducing:**
[Plnk](https://embed.plnkr.co/McAlXVoarLPIKKx6IUxH/)

**Comment by smnbbrv** [comment]
Hi, please create a plunkr or github repo reproducing the problem

**Comment by eslammahgoub** [comment]
Here is the plunkr [Plnk](https://embed.plnkr.co/McAlXVoarLPIKKx6IUxH/)

**Comment by smnbbrv** [comment]
Hi @eslammahgoub 

I think the reason is that `mat-grid-list` is wrapping a children content into some `div`. Sortable is taking this div and allows to sort it but the problem is that you want to sort the div content and not the div itself. I tried to apply various options from https://github.com/RubaXa/Sortable , e.g. `draggable` but it still does not seem to work because it expects element with `[sortablejs]` to be the parent of sortable children.

I couldn't manage to do that, sorry :( If you find some way to work this around or have some proposal how to fix this as a feature - please share it here

**Comment by smnbbrv** [comment]
implemented as sortablejsContainer in 3.1.0
